services:
  traefik:
    image: traefik:v3.7.1
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=your-email@example.com" # Change this!
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - gitea_net

  gitea:
    image: gitea/gitea:1.26
    container_name: gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__server__ROOT_URL=https://lenpc.dsystems/
      - GITEA__server__HTTP_PORT=3000
    volumes:
      - ./gitea-data:/data
    networks:
      - gitea_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`lenpc.dsystems`) || Host(`lenpc-remote.dsystems`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.tls.certresolver=myresolver"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"

  gitea-runner:
    build:
      context: .
      dockerfile: runner.Dockerfile
    container_name: gitea-runner
    restart: always
    user: "0:0"
    environment:
      - GITEA_INSTANCE_URL=http://gitea:3000
      - GITEA_RUNNER_REGISTRATION_TOKEN=gOWEI9Qanikvrp6RHuSBK8mU1YXo6JXyoWosuoM5
      - GITEA_RUNNER_NAME=local-runner
      - GITEA_RUNNER_LABELS=self-hosted
    volumes:
      - ./runner-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitea_net
    depends_on:
      - gitea

networks:
  gitea_net:
    driver: bridge
